### ISSUE TITLE
Issue with Auto-Generated Karate Feature Files: Schema Validation and Field Generation

### ISSUE THREAD

**Issue by Mohitkrishna12** [ZenWave360/karate-ide#30]
Hi @ivangsa ,
Auto-generated Karate feature files often include optional fields with fuzzy matching, despite being marked as required in the schema. 
```
{
  "id": "##number",
  "name": "##string",
  "status": "##string"
}
```
This issue revolves around the utilization of the _**buildKarateSchema**_ function found within the **test-data-generator.ts** file. 
 ```
    const required = options.requiredProps && options.requiredProps.includes(options.name);
    const nullable = schema.nullable === true || (Array.isArray(schema.type) && schema.type.includes("'null'"));
    const isOptionalPrefix = !required || nullable ? '#' : '';
```
In the above code required is always false because in the function call **options** parameter is empty object '{}'. Please review this issue. Correct me if I'm mistaken. Additionally, could you confirm whether it's possible to implement max length, min length, and regex pattern validations based on the schema of the spec file during the generation process?. I'm also open to contributing to address this matter if such assistance is needed.

**Comment by ivangsa** [comment]
Currently there are not unit-test but since `test-data-generator.ts` does not depend on vscode it could be easy to add a test for this.

Any way to start the extension in debug mode you need two steps:
- Run: `npm run watch` and keep it open
- On vscode press `F5` or from Run&Debug run `Run Extension`. This will open a new vscode instance with the extension in dev mode, you can open any workspace on this instance and use the extension while you can place breakpoints on the vscode instance holding your source code

For this issue you just need to build an array of "operation response required fields" you can get from `operation` parameter (which is the openapi operation) and pass it inside the `options` variable you pointed out is empty...

If you have any question just let me know..

**Comment by ivangsa** [comment]
yes you are right, `matchResponse`  should be set to true only for 2xx because you don't usually need to match the response payload against the schema for codes like 400,404...

So you mean generate something like this:

<img width="296" alt="image" src="https://github.com/ZenWave360/karate-ide/assets/1246876/214171ac-6079-4546-93d1-c2e2ba4b4674">

Yes I think this is very useful.. go ahead!

**Comment by Mohitkrishna12** [comment]
Hi @ivangsa ,
I've submitted the Pull Request to address the discussed issues. Your feedback is much appreciated. Thanks!

**Comment by ivangsa** [comment]
Your PR has been merged and published to vscode marketplace: https://marketplace.visualstudio.com/items?itemName=KarateIDE.karate-ide

Thanks a lot!! If you find the extension useful maybe you can leave a review or rate it in the marketplace..
